---
## used by Loki to authenticate with keyvault to
## retrieve access key for Azure blob storage

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: monitoring-kv-access
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 0f4358c5-c2d0-47a5-8405-f47e11c41bc3
    resourceGroup: monitoring-core-uks-rg-1
    keyvaultName: monitor-core-uks-kv-01
    objects: |
      array:
        - |
          objectName: loki-blob-access-key
          objectType: secret
    tenantId: 629ba906-d77e-4dc6-acf3-d71375b281ea
  secretObjects:
    - data:
        - key: AZURE_STORAGE_ACCESS_KEY
          objectName: loki-blob-access-key
      secretName: loki-csi-kv-secret
      type: Opaque

---
## used by grafana to inject client_id and client_secret for Azure OAuth

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: monitoring-gf-oauth-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 0f4358c5-c2d0-47a5-8405-f47e11c41bc3
    resourceGroup: monitoring-core-uks-rg-1
    keyvaultName: monitor-core-uks-kv-01
    objects: |
      array:
        - |
          objectName: grafana-core-client-id
          objectType: secret
        - |
          objectName: grafana-core-client-secret
          objectType: secret
    tenantId: 629ba906-d77e-4dc6-acf3-d71375b281ea
  secretObjects:
    - data:
        - key: GF_AUTH_AZUREAD_CLIENT_ID
          objectName: grafana-core-client-id
        - key: GF_AUTH_AZUREAD_CLIENT_SECRET
          objectName: grafana-core-client-secret
      secretName: grafana-azuread-auth
      type: Opaque

---
## used by promtail to add basic auth to requests destined for loki gateway

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: monitoring-promtail-auth-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 0f4358c5-c2d0-47a5-8405-f47e11c41bc3
    resourceGroup: monitoring-core-uks-rg-1
    keyvaultName: monitor-core-uks-kv-01
    objects: |
      array:
        - |
          objectName: loki-basic-auth-user
          objectType: secret
        - |
          objectName: loki-basic-auth-password
          objectType: secret
    tenantId: 629ba906-d77e-4dc6-acf3-d71375b281ea
  secretObjects:
    - data:
        - key: LOKI_BASIC_AUTH_USER
          objectName: loki-basic-auth-user
        - key: LOKI_BASIC_AUTH_PASSWORD
          objectName: loki-basic-auth-password
      secretName: loki-gateway-creds
      type: Opaque

---
## used by Mimir to authenticate with keyvault to
## retrieve access key for Azure blob storage

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mimir-kv-access
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 0f4358c5-c2d0-47a5-8405-f47e11c41bc3
    resourceGroup: monitoring-core-uks-rg-1
    keyvaultName: monitor-core-uks-kv-01
    objects: |
      array:
        - |
          objectName: mimir-blob-access-key
          objectType: secret
    tenantId: 629ba906-d77e-4dc6-acf3-d71375b281ea
  secretObjects:
    - data:
        - key: AZURE_STORAGE_ACCESS_KEY
          objectName: mimir-blob-access-key
      secretName: mimir-csi-kv-secret
      type: Opaque

---
## used by Tempo to authenticate with keyvault to
## retrieve an access key for Azure blob storage

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tempo-kv-access
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 0f4358c5-c2d0-47a5-8405-f47e11c41bc3
    resourceGroup: monitoring-core-uks-rg-1
    keyvaultName: monitor-core-uks-kv-01
    objects: |
      array:
        - |
          objectName: tempo-blob-access-key
          objectType: secret
    tenantId: 629ba906-d77e-4dc6-acf3-d71375b281ea
  secretObjects:
    - data:
        - key: AZURE_STORAGE_ACCESS_KEY
          objectName: tempo-blob-access-key
      secretName: tempo-csi-kv-secret
      type: Opaque
