---

## used by promtail to add basic auth to requests destined for loki gateway

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: monitoring-promtail-auth-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          
    userAssignedIdentityID: 827d64e3-0bdd-465b-a3f9-25f50d09976d
    resourceGroup: monitoring-core-uks-rg-1
    keyvaultName: monitor-core-uks-kv-01
    objects:  |
      array:
        - |
          objectName: loki-basic-auth-user
          objectType: secret
        - |
          objectName: loki-basic-auth-password
          objectType: secret                         
    tenantId: 629ba906-d77e-4dc6-acf3-d71375b281ea
  secretObjects:
  - data:
    - key: LOKI_BASIC_AUTH_USER
      objectName: loki-basic-auth-user
    - key: LOKI_BASIC_AUTH_PASSWORD
      objectName: loki-basic-auth-password
    secretName: loki-gateway-creds
    type: Opaque
