---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  releaseName: blackbox-exporter
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  values:
    resources:
      requests:
        memory: 50Mi
      limits:
        memory: 100Mi
