---
## Personal AKS learning setup:
## keep this file, then replace placeholders with your personal Key Vault details.
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: monitoring-gf-oauth-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<USER_ASSIGNED_IDENTITY_CLIENT_ID>"
    resourceGroup: "<AKS_RESOURCE_GROUP>"
    keyvaultName: "<KEYVAULT_NAME>"
    objects: |
      array:
        - |
          objectName: grafana-client-id
          objectType: secret
        - |
          objectName: grafana-client-secret
          objectType: secret
    tenantId: "<TENANT_ID>"
  secretObjects:
    - data:
        - key: GF_AUTH_AZUREAD_CLIENT_ID
          objectName: grafana-client-id
        - key: GF_AUTH_AZUREAD_CLIENT_SECRET
          objectName: grafana-client-secret
      secretName: grafana-azuread-auth
      type: Opaque
